Strong number
To check weather a number is strong or not
=> Strong number

Binary To Decimal.c
Improved the readability of the program.
=> Update Binary to Decimal.c

palindrome.c
I have given a solution for palindrome in C
=> Updating solution for Palindrome

BubbleSort.c
1- The array filling is done dynamically using realloc() function
2- The Algorithm is optimized by remplacing the double for loops with a for inside a while loop
=> Optimizing the algorithm, and improving the array filling

sorting/shaker_sort.c
This is folder for sorting algorithm in C and have added shaker sort and soon will be adding more sortings
=> Shaker Sort 

misc/rselect.c, sorting/mergesort.c.c, sorting/qiksort.c
=> added mergesort,quicksort,randomized selection

fat.c, fib.c
I saw that in the java version there was the factorial algorithm, so, i thought that it would be nice to have the same but this time made with C. And I also made a Fibonacci algorithm that asks for a number and than it tells which number is in the N position according to the Fibonacci sequence. Hope you like it :)
=> Add 2 more algorithms (Fibonacci and Factorial)

Sorts/QuickSort.c
Quick sort implemented in C with comments, and proper naming.
=> Added Implementation of quick sort

TowerOfHanoi.c
I was added new recursive algorithm called as Tower of Hanoi
=> Added a new file

data_structures/linked_list/singly_link_list_deletion.c
#37 
I have Added A new folder for Linked list with a complete working C program to demonstrate deletion in singly linked list.
=> Singly Linked list deletion

Searches/Jump_Search.c, Sorts/HeapSort.c
I added heapsort.c file, jumpsearch file to sorts folder and search folder. 
There seems to be no difference except to enter the size of the array when compared to a Python file.
Please check and pull request. I want your feedback.
=> add heapsort to sorts folder

Searches/Jump_Search.c, Searches/Other_Binary_Search.c, Sorts/HeapSort.c
correct compilation error and logic error at Otherbinarysearch in search folder
I want your opinion and feedback.
I'd like you to tell me if there's anything you do not like.
=> correct compilation error and logic error at Otherbinarysearch in search folder

Data Structures/stack/README.md, Data Structures/stack/main.c, Data Structures/stack/stack.c, Data Structures/stack/stack.h
=> simple modular and generic stack

primes.c
This commit adds a sieve of Eratosthenes algorithm.
This is for issue #37
=> Add Sieve of Eratosthenes

sorting/HeapSort.c
I write my own implement of heap sort. Follow my teacher guide in university.
=> Add heap sort

Searches/interpolation_search.c
Interpolation search implemented in c
=> interpolation.c

Data Structures/stack/balanced parenthesis using stack in C
this C program checks whether brackets are balanced or not in an string
=> balanced parenthesis using stack in C

misc/Collatz.c, misc/catalan.c, misc/factorial_trailing_zeroes.c
Three new codes:
1.Catalan numbers.
2.Factorial_trailing_zeroes
3.Collatz conjecture
=> Add three new codes 

Conversions/decimal _to_binary.c, Data Structures/Array/CArray.c, Data Structures/Array/CArray.h, Data Structures/Array/CArrayTests.c, Data Structures/Array/README.md
Array of integers with Insert, Remove, Update, Erase, Switch, Reverse functions; Sorting functions like BubbleSort, InsertionSort and SelectionSort; and Search functions like FindMin, FindMax, Frequency count, etc.
=> Array Data Structure

Data Structures/Array/CArray.c, Data Structures/Array/CArray.h
Instead of using return codes and commenting what they mean, I replaced them with easy-to-identify macros in the Array directory.
=> Replaced ambigous return codes with macros.

sorting/BubbleSort.c, sorting/InsertionSort.c, sorting/SelectionSort.c
The codes in sorting have different forms.
I formulated BubbleSort.c, InsertionSort.c, SelectionSort.c by QuickSort.c
=> Formulate codes in Sort

exercism/hello-world/hello_world.c
The solution presented is correct. However, for the sake of good practice, it is important that we check whether a call to `malloc` or `calloc` is successful.
=> Added NULL check.

misc/PrimeFactoriziation.c
* I added a new algorithm for [prime factoriziation](https://en.wikipedia.org/wiki/Prime_number#Unique_factorization) of a positive integer greater than 1.
=> Prime factoriziation

README.md, misc/PrimeFactoriziation.c
* I changed the README. Added the name of the new algorithm.
* I corrected some comments in the source code.
=> changed README and corrected comments -- Prime Factoriziation

data_structures/stack/main.c
* I refactored the file ```data_structures/stack/main.c```.
=> refactoring stack/main.c

sorting/shellSort.c
Data Sorted
Shell Sort Big O Notation:
--> Best Case: O(n log(n))
--> Average Case: depends on gap sequence
--> Worst Case: O(n)
Time spent sorting: 0.000006
*** stack smashing detected ***: <unknown> terminated
Aborted
=> BugFix : loop out of range will cause stack smashing

sorting/partitionSort.c
Hi,
I make PR for adding partition sort algorithm.
=> Add partition sort algorithm

searching/pattern_search/naive_search.c, searching/pattern_search/rabin_karp_search.c
=> Pattern Search

searching/pattern_search/Makefile, searching/pattern_search/boyer_moore_search.c
Hi, 
I make PR to add Boyer Moore search algo and simple Makefile
=> Add Boyer Moore search algo and simple Makefile

data_structures/stack/stack.c
Thanks for giving me the opportunity for the first PR. I think I think I have solved the problem of on free.
=> fix the stack.c

README.md, sorting/radixsort.c
Added radix sort and formatted the code (was previously marked for this).
=> Sorting and README.md updates

sorting/comb_sort.c
I've cleaned up the previous PR
=> Add comb sort

sorting/gnome_sort.c
I've cleaned up my previous PR.
=> Add gnome sort

sorting/gnome_sort.c
Now they should all be C89-compatible.
=> Fix for loop in gnome_sort to make it C89-compatible

leetcode/771.c, leetcode/README.md, leetcode/src/771.c
Added solution to Leetcode problem 771. Jewels and Stones in reference to issue #249
=> added solution to Leetcode problem 771.Jewels and Stones

data_structures/graphs/BFS.c
Added the **BFS** algorithm in **graphs** section, which seems very lacking. Please review it and merge if found useful 😁 
The Sample I/O from an execution is as below:
=> Added BFS algorithm

data_structures/graphs/DFS.c
Following **BFS**, here is contribution to the **DFS** algorithm. Kindly let me know if any changes are needed 😄 
Please refer to the image below for a sample I/O.
=> Added DFS algorithm

data_structures/graphs/topologicalSort.c
Hi, this is my attempt at adding the code for topological sorting of a graph. 
A sample I/O of the program is:
Please review and merge if found useful. Any type of feedback welcome 😄
=> Added Topological Sorting

data_structures/heap/minheap.c
Added the min-heap data structure. Kindly check and merge if found useful.
=> Adding min heap

data_structures/binary_trees/redBlackTree.c
:sparkles:  This is a C Program that implements Red Black Trees. It contains functions for Insertion, Deletion, and Inorder Traversal.
=> Adding Code for Red Black Tree

README.md, project_euler/Problem 04/sol.c, project_euler/Problem 05/sol.c, project_euler/Problem 06/sol.c, project_euler/Problem 07/sol.c
=> Project Euler Solution

data_structures/graphs/strongly_connected_components.c
Hi, added the code for finding all strongly connected components in a graph. Please review and merge if found useful.
=> Added code to find strongly connected components

leetcode/README.md
Fixed a couple which were out of order and added #1 which was missing.
=> Update more leetcode solution

sorting/multikey_quicksort.c
Wikipedia entry can be found [here](https://en.wikipedia.org/wiki/Multi-key_quicksort).
Official paper can be found [here.](https://www.cs.princeton.edu/~rs/strings/paper.pdf)
Based on demo program [here.](https://www.cs.princeton.edu/~rs/strings/demo.c)
=> Added multikey quicksort

leetcode/README.md, leetcode/src/173.c
In reference to issue https://github.com/TheAlgorithms/C/issues/249
=> Solution to Leetcode Problem 173

leetcode/README.md, leetcode/src/1189.c
As requested on https://github.com/TheAlgorithms/C/issues/249
Add solution to problem 1189 Maximum Number of Ballons available at: https://leetcode.com/problems/maximum-number-of-balloons/
Also updated README from leetcode folder.
=> 249 add maximum number of ballons

leetcode/README.md, leetcode/src/461.c
Another solution for https://github.com/TheAlgorithms/C/issues/249
=> Added commented solution to problem 461

leetcode/src/1189.c, leetcode/src/283.c, leetcode/src/617.c, leetcode/src/700.c, leetcode/src/704.c, leetcode/src/771.c, leetcode/src/82.c, leetcode/src/905.c, leetcode/src/938.c, leetcode/src/977.c
The for loop utilized in 283 was improperly structured as 'start'
was no declared as the value to index.
Also, make the other cases more readable.
=> leetcode: Address readability of a few cases, and fix 283

leetcode/README.md, leetcode/src/476.c
Another solution for https://github.com/TheAlgorithms/C/issues/249
=> Added commented solution to Leetcode problem 476

searching/LinearSearch.c
Cleaned up the code and used meaningful variable names
=> Cleaned up, meaningful variable names

CodingGuidelines.md, README.md
=> updated README.md

README.md, misc/Primes_in_range.c
Added a new file - Primes_in_range.c in `misc` folder.
It uses the sieve of Eratosthenes algorithm to get all the prime numbers in a given range
=> Added primes_in_range.c. Edit: no conflicts with base branch 

Conversions/decimal-to-binary-without-array.c, conversions/decimal_to_binary_without_array.c
Decimal to binary without array.
=> Created a new file of conversion without array.

sorting/BubbleSort.c
Here the time complexity of bubble sort is added
=> Time Complexity Added

sorting/HeapSort.c
Added comments and updated heap_sort  function 
In heap_sort function after heapifying unsorted array while creating a sorted array (from second for loop)
the last element is not sorted as i is defined as >0 so it should be changed to i>=0.
=> Error in heap_sort function while sorting

sorting/random_quick_sort.c
✨ This is the implementation of Randomised Quick Sort Algorithm in C language.
=> Code for Randomised Quick Sort

leetcode/README.md, leetcode/src/4.c
Added C solution for problem No. 4. Median of two sorted arrays (Difficulty: Hard)
Beats 70% of total solutions in terms of both runtime and storage
=> Median of two sorted arrays No. 4 

hash/README.md, hash/hash.c, hash/hash.h, hash/test_program.c
Hi everyone, i implemented the CRC-32 Checksum Algorithm for **hash.c**
Files changed:
- hash/hash.c
- hash/hash.h
- hash/README.md
=> Implementet CRC-32 Checksum Algorithm

leetcode/README.md, leetcode/src/28.c
Adding KMP algorithm implementation for searching pattern in string
leetcode problem no: 28
#249
=> KMP algorithm implementation for string search

leetcode/README.md, leetcode/src/2.c, leetcode/src/21.c
Leetcode Solution:
Problem 2: Add Two Numbers
Problem 21: Merge Two Sorted Lists
#249
=> Solution for Leedcode problem 2 and 21

leetcode/README.md, leetcode/src/13.c, leetcode/src/201.c, leetcode/src/29.c, leetcode/src/66.c
Leetcode Solution:
- Adding Roman to Integer (13.c)
- Adding Divide Two Integers (29.c)
- Adding Plus One (66.c)
- Adding Bitwise AND of Numbers Range (201.c)
- Readme updated
#249
=> Solution for Leedcode problem 13, 29, 66 and 201

leetcode/README.md, leetcode/src/12.c, leetcode/src/8.c
Leetcode Solution:
Problem 8: String to Integer (atoi)
Problem 12: Integer to Roman
#249
=> Add leetcode String to Integer (atoi) (8.c) and Integer to Roman (12.c)

leetcode/README.md, leetcode/src/11.c
Solved problem 11 on LeetCode. For issue #249
=> added solution and modified README.md for problem 11

misc/lerp.c
Added a simple linear interpolation algorithm and sample main function.
=> [added] lerp, with both an unprecise and a precise option.

README.md, misc/pid.c
This PR adds the PID Controller - a common (and likely most ubiquitous) linear control systems algorithm. For now, since there are no other control algorithms present in the repo, I have added it into the `misc` folder. Apologies if this is slightly out of scope of your definition of algorithms, but I figured if the client server socket example was in scope, then this likely would be too.
More information about the PID Controller can be found here: https://en.wikipedia.org/wiki/PID_controller
Thanks, Ciaran
=> Add PID (Proportional Integral Derivative) Controller

Simple Client Server/UDPClient.c, Simple Client Server/UDPServer.c
#305 Added  for UDP Client - Server Program.
Hope this Helps everyone.
=> UDP Client Server algorithm implementation in C

searching/ternarysearch.c
Added a new search algorithm- Ternary Search.
=> added ternary search algorithm

sorting/countingSort.c
Added description about advantage of counting sort over comparison sort and
how counting sort can be stabilized.
=> Indented "counting Sort" and fixed compilation errors

sorting/HeapSort.c
So I copied the C++ version from TheAlgorithms and re-wrote it in C.
Now it works.
=> heapsort does not work for sorted input 1,2,3,4,5

sorting/gnome_sort.c
Please review and suggest changes if my solution doesn't take care of the issue.
=> index now starts from 1

sorting/Cocktail_Sort.c, sorting/Pigeon_Sort.c, sorting/Pigeonhole_Sort.c
I added some new sorting algorithms.
1. Pigeonhole Sort
2. Cocktail Sort
=> Added Sorting Algorithms

conversions/octal_to_decimal.c
Added an example for octal to decimal.
=> Octal to Decimal

data_structures/Array/README.md
Please add this, because there  many programmers who are beginners. So, for their understanding please add this.
=> Added definition or meaning of "Sort Function".

greedy_approach/djikstra.c
added djikstra's algorithm in c , solves issue #487
=> added file for djikstars's in /greedy_approach

misc/Factorial.c
Changed Code for Factorial.c , extending its ability to calculate factorials for larger numbers.
Previous code threw out error for input of negative numbers for factorials, not it displays an apt message.
=> Modified code of misc/Factorial.c to accomodate larger numbers.

exercism/hello_world/hello_world.c
strdup can always make your life easier
=> make strdup handle string alocation

sorting/binary_Insertion_Sort.c
=> improved library

sorting/binary_Insertion_Sort.c
Reverts TheAlgorithms/C#542 due to some problem in description
=> Revert "improved library"

machine_learning/adaline_learning.c, machine_learning/kohonen_som_topology.c, machine_learning/kohonen_som_trace.c
* Update documentation of machine learning algorithms
* Group functions and members related to machine learning algorithms
Notes:
=> [docs] Update documentations in machine learning

sorting/bead_sort.c, sorting/shell_sort2.c
added `sorting` group in documentation
Notes:
=> [docs] add documentation group

misc/fibonacci_fast.c, misc/sudoku_solver.c, project_euler/problem_19/sol1.c, sorting/merge_sort.c
* Sudoku file used multiple global variables with ambiguous names and had no documentation. 
These issues have been fixed. Moreover, extensive documentation and debug messages have been added.
* More documentation and LGTM alerts fixes for:
* fibonacci_fast
* project euler problem 19
* merge_sort
* also fixed dynamic memory de-allocation
* Part of efforts for #550 
* original commit for sudoku: 97f8c4a782d80f1afb0a7a0881b11c98968ae57f
Notes:
=> [bugs & docs] lots of documentation and bug fixes

README.md
README.md file made more elaborate as in the [C++ repo](https://github.com/TheAlgorithms/C-Plus-Plus/README.md)
[README.md from C++ repo](https://github.com/TheAlgorithms/C-Plus-Plus/README.md)
Notes:
=> [enhancement] more elaborate README

sorting/gnome_sort.c
Pull-request #513 was incorrectly merged adding to errors in the original implementation. This *un-does* the pull-merge and restores to working and valid algorithm.
Notes:
=> [Bug] gnome sort: reverted merge commit adding error

misc/cartesian_to_polar.c, misc/union_find.c, searching/jump_search.c
Files fixed for LGTM alerts. The alerts and fixes will be reported in comments below by LGTM.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/565"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C.git/47958fb003b8462bad3e8b58292e049164781925.svg" /></a>
=> [LGTM alerts] fixes to some of the LGTM alerts

misc/palindrome.c
Rewrited palindrome algorithm using function
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/567"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shellhub/C.git/ff90d873d35531cd47f48f4c6cd6a79617a86999.svg" /></a>
=> add isPalindrome function

.github/workflows/awesome_workflow.yml, project_euler/problem_13/sol1.c, project_euler/problem_23/sol1.c, project_euler/problem_23/sol2.c, project_euler/problem_25/sol1.c, project_euler/problem_401/sol1.c
Fixed some files for errors and warnings reported by clang-tidy.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/568"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C.git/f58916f8f51087ca644dd5703bad2b2b6777626d.svg" /></a>
=> [bugs] cleanup some codes for global variables and clang-tidy specs

DIRECTORY.md, sorting/bubble_sort_recursion.c
Bubble sort algorithm implments using recursion
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/574"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shellhub/C.git/9728ca7f51eac8b57ba43e9d5a495f244710ca49.svg" /></a>
=> Bubble sort recursion

sorting/bubble_sort.c
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/573"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shellhub/C.git/0df9729638ccb816f6ed6fe96085237a8082f416.svg" /></a>
=> bubble sort optimization

.github/workflows/awesome_workflow.yml, data_structures/binary_trees/binary_search_tree.c
Added docs and fixed errors in the code
Closes #566 
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/579"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C.git/1cd54a593b7b1d7b06bf1ad32d6bcf0e23d29491.svg" /></a>
=> [bug+docs] add docs + fix error in getMax

DIRECTORY.md, conversions/decimal_to_binary_recursion.c
Add decimal to binary using recursion algorithm
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/575"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shellhub/C.git/d93a930ef93fde801eb4ecde818a6c893f54e8b1.svg" /></a>
=> decimal to binary using recursion

sorting/insertion_sort.c, sorting/selection_sort.c
* fix docs
* optimization
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/587"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shellhub/C.git/10d006c3b10340b901860e4810d2122b10e35b76.svg" /></a>
=> [fix] insertion and selection sort

machine_learning/k_means_clustering.c
Implemented K Means Clustering in C
The data set used for implementing is ordered pair(x,y) in 2D plane.
Notes: 
The Link Checks are always failing I am really unable to understand why
If you can refer some resources to learn about it that would be really helpful.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/589"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Lakhan-Nad/C.git/74cf22122a3f5d97389bfb4f22293827987209c2.svg" /></a>
=> feat: K Means Clustering Added

machine_learning/k_means_clustering.c
This fixes the documentation from the code in #589 
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/592"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C.git/858b6429eba83ebe69eea0755f68bf998c1e475d.svg" /></a>
=> [doc fix] fix documentations in k_means 

DIRECTORY.md, data_structures/binary_trees/segment_tree.c
Added segment_trees code with a test on RMQ
Issue: #561 
Notes: 
Any change or update is welcome. If my code seems less documented please let me know where should I change.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/595"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Lakhan-Nad/C.git/3da4ff21f643273161f121ddcee7b3e4c1a44cae.svg" /></a>
=> Feature: Added segment_trees Closes #561

sorting/multikey_quick_sort.c
- Fix [LGTM](https://lgtm.com/projects/g/TheAlgorithms/C/alerts) warning/alert.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/601"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Panquesito7/C.git/8748c2e002c90c4d06aa49f60f2a4ac2a971797f.svg" /></a>
=> fix: LGTM warning/alert

DIRECTORY.md, misc/power.c, misc/power_recursion.c
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/604"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shellhub/C.git/bab150802deaff5460ea6a6a8da4cf463aaee2ea.svg" /></a>
=> Added math function power

DIRECTORY.md, strings/strlen.c, strings/strlen_recursion.c
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/606"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shellhub/C.git/b9bab8d07f8ebab49379c930cfd270d54f989ad8.svg" /></a>
=> Added strlen function

CODE_OF_CONDUCT.md
- Added Code of Conduct.
None
Notes: Code of Conduct from the https://github.com/TheAlgorithms/.github repository.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/636"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Panquesito7/C.git/812702ff45db3a51ee9571a1f7953d3244c70c52.svg" /></a>
=> [fix/feat]: Added Code of Conduct

DIRECTORY.md, conversions/octal_to_binary.c
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/629"><img src="https://gitpod.io/api/apps/github/pbs/github.com/vishnu0pothan/C.git/a28d6b3787e12908e21b92507f4a901110b7c191.svg" /></a>
=> Added octal to binary conversion

sorting/insertion_sort_recursive.c
Adding algo for insertion sort using recursive
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/647"><img src="https://gitpod.io/api/apps/github/pbs/github.com/itsvinayak/C.git/aa2a9727a4f1f8e9a6df079eee1bc3eae03cdcd5.svg" /></a>
=> insertion_sort_recursive

REVIEWER_CODE.md
Added guidelines for reviewers.
Discussion: https://gitter.im/TheAlgorithms/community?at=5f83112999e1ab4dd1f1d9e8
- ~[ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)~
- ~[ ] Added tests and example, test must pass~
- ~[ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)~
- ~[ ] Relevant documentation/comments is changed or added~
- ~[ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)~
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/671"><img …
=> feat: guidelines for reviewers

DIRECTORY.md, conversions/hexadecimal_to_octal2.c
Now input supports the whole range of `uint64_t`, from `0` to `FFFF FFFF FFFF FFFF`.
This first converts a hex string to an `unsigned long long` decimal, and then to an octal string.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/658"><img src="https://gitpod.io/api/apps/github/pbs/github.com/yous/TheAlgorithms-C.git/df1b119b70b57dccf803f7f098252cdec24e9338.svg" /></a>
=> Add another hexadecimal to octal conversion

conversions/binary_to_decimal.c
First printf(): newline character changed from /n to \n
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/730"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nicola-masarone/C.git/d35c2293a0459b070d9a1e9e9d991a0cd302f55b.svg" /></a>
=> fix: Update conversions/binary_to_decimal.c

DIRECTORY.md, misc/prime_seive.c
This function counts the number of prime numbers in O(nlogn) time.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/708"><img src="https://gitpod.io/api/apps/github/pbs/github.com/webdesignbydivyansh/C.git/d3e1e3052aafc76f42d6179197b936c01883e5e8.svg" /></a>
=> feat: created prime_seive.c

data_structures/array/README.md
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/779"><img src="https://gitpod.io/api/apps/github/pbs/github.com/imba-tjd/C.git/8892e1b57f13d02cf20aa6189d409300b12d5faa.svg" /></a>
=> docs: fix md style

LICENSE
- Update the copyright year to 2021.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/780"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Panquesito7/C.git/6f82b6fafb56026f865c90c04a6749dce1b8236f.svg" /></a>
=> fix: Update the copyright year to 2021

data_structures/array/carray.c, data_structures/array/carray_tests.c
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/783"><img src="https://gitpod.io/api/apps/github/pbs/github.com/RavishankarreddyB/C.git/dd38f53f1e94524480a9652e1de91b59f76f9d62.svg" /></a>
=> Header name fix

data_structures/linked_list/stack_using_linked_lists.c
Improve source code formatting at data_structures/linked_list/stack_using_linked_lists.c
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/768"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Suraj-Patro/C.git/752cde71ef71e8c0fa80bc3168f2932b4be3b669.svg" /></a>
=> fix: Improved source code formatting at data_structures/linked_list/stack_using_linked_lists.c

conversions/octal_to_binary.c
Source Code formatting in `conversions/octal_to_binary.c`.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/744"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Suraj-Patro/C.git/f23987e8ce7334e82acc66c2fceff4d213d8ae47.svg" /></a>
=> fix: Improved code formatting in conversions/octal_to_binary.c

DIRECTORY.md, conversions/octal_to_hexadecimal.c
Implemented Octal to Hexadecimal conversion using C
#633
[x] Added description of change
[x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
[x] Added tests and example, test must pass
[x] Relevant documentation/comments is changed or added
[x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
[x] Search previous suggestions before making a new one, as yours may be a duplicate.
[x] I acknowledge that all my contributions will be made under the project's license.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/677"><img src="https://gitpod.io/api/apps/github/pbs/github.com/rachitbhalla/C.git/f2c9fe3ee552 …
=> Implemented octal to hexadecimal conversion

sorting/bubble_sort_2.c
As of now, the implementation of the bubble-sort algorithm in [bubble_sort2.c](https://github.com/TheAlgorithms/C/blob/master/sorting/bubble_sort_2.c) is not working.
```c
int i, arraySort[MAX] = {0}, isSort = FALSE, changePlace;
// ...
while (isSort) { // sorting code... }
```
The above snippet illustrates the problem. The flag `isSort` is initially set to [`FALSE`](https://github.com/TheAlgorithms/C/blob/master/sorting/bubble_sort_2.c#L5) and, consequently, the loop where the array would be sorted never runs. Other than that, we can also see _camelCase_ being used and the lack of a separate test function and documentation as per `CONTRIBUTING.md` [instructions](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#typical-structure-of-a-program).
=> [feat/fix/docs]: Fix bubble_sort2.c implementation bug and some documentation/structure improvements

DIRECTORY.md, games/naval_battle.c
Naval battle done in C
https://pt.wikipedia.org/wiki/Batalha_naval_(jogo)
Notes: 
Solution in C 
output example : https://prnt.sc/yfo4b1
=> feat: added naval_battle, to games.

numerical_methods/mean.c
Fixed a possible segmentation fault when no argument is provided. Additionally, made tiny changes to print statements.
=> fix: possible segmentation faults in `numerical_methods/mean.c`

conversions/c_atoi_str_to_integer.c
Notes: fixed previous commit from another user (added `i++`). was assert-fail on negative numbers.
=> fix: assertion failed on negative numbers in `conversions/c_atoi_str_to_integer.c`

DIRECTORY.md, sorting/selection_sort_recursive.c
=> feat: added selection_sort_recursive.c

DIRECTORY.md, sorting/heap_sort_2.c
=> feat: created heap_sort_2.c

DIRECTORY.md, searching/exponential_search.c
- added Exponential Search Algorithm
Notes: implementation of Exponential Search
=> feat: Exponential Search

DIRECTORY.md, greedy_approach/prim.c
I implemented prim's algorithm and added `prim.c` to `TheAlgorithms/C/greedy_approach`. 
Prim's algorithm finds a minimum spanning tree of a weighted, connected graph. 
Using a 'greedy' approach to generate the MST, the algorithm searches for a minimally weighted, non-visited edge, and adds the vertex connected by that edge to the MST.
To test, compile and run.
Enter in adjacency matrix of a weighted, connected graph.
pg. 319 "Introduction to the Design and Analysis of Algorithms" - Anany Levitin
- [x ] Added description of change
- [x ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ x] Added tests and example, test must pass
- [ x] Relevant documentation/comments is changed or added
- [ x] PR title …
=> feat: Prims algorithm

.github/workflows/approved-label.yml
Things added/changed:
- Add the `Approved Label` workflow
- When a pull request is approved, it'll automatically add the `approved` label.
- ~[ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)~
- ~[ ] Added tests and example, test must pass~
- ~[ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)~
- ~[ ] Relevant documentation/comments is changed or added~
Notes: A The Algorithms maintainer, should approve the PR to see if the workflow works as excepted.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/830"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Add the `Approved Label` workflow

CONTRIBUTING.md
- Improve the contributing guidelines.
- Mostly all of the changes are taken from https://github.com/TheAlgorithms/C-Plus-Plus/pull/1503.
TheAlgorithms/C-Plus-Plus#1503
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/839"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [feat/fix]: Improve the contributing guidelines

geometry/vectors_3d.c
a function get_angle is added for the vector3d to calculate the angle between two given vector
test and doc added for this function as well
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/838"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> tests: added `get_angle` test function in geometry/vector3d

README.md
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/842"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: Changes in README

DIRECTORY.md, searching/floyd_cycle_detection_algorithm.c
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/844"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Add floyd cycle-detection-algorithm to find duplicate number

machine_learning/adaline_learning.c
improving this file
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/846"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Add endlines in `machine_learning/adaline_learning.c`

DIRECTORY.md, sorting/odd_even_sort.c
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/855"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Odd Even Sorting Algorithm

CMakeLists.txt, DIRECTORY.md, audio/CMakeLists.txt, audio/alaw.c
1. add G.711 a-law algorithm
2. add audio/
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/858"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: add G.711 a-law algorithm

.github/workflows/stale.yml
Add stale workflow that'll close old issues/PRs
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/860"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Add stale workflow

CODE_OF_CONDUCT.md
- Update the CoC to match the `.github` repository.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/913"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Update the CoC to match the `.github` repository

.gitpod.yml
- Update Gitpod extensions.
#915
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/917"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Update Gitpod extensions

games/tic_tac_toe.c
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/920"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: remove redundant space before comma

leetcode/src/3.c
fix typos in comments of leetcode/src/3.c
Notes: 
fix typos in comments of leetcode/src/3.c
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/931"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: typo in comments of leetcode-3

data_structures/trie/dictionary.txt, data_structures/trie/trie.c
The trie example had some issues;
* It did not follow the code convention in CONTRIBUTING.md
* The createTrieNode used an inefficient zeroing method (looping over
the entries) which also does not zero out holes in the structure (e.g.
an alternative would be to use "*node = &(TrieNode){0}", but calloc
does all that anyway
* It used an inefficient and clumsy printArray method
* It used strlen inside the algorithm; this new method could get rid of
any strlen/strnlen usage (inserts/searches could be sanitized by
snprintf)
* This version can allow for a custom mapping function, e.g. if NULL is
a valid separator (say that you want a trie for certain binary
packages)
* The previous version actually contained out-of-bounds array indexing;
there were no checks for out-of-bound indexing and words …
=> Rewrite the trie example

client_server/tcp_full_duplex_client.c, client_server/tcp_full_duplex_server.c, data_structures/binary_trees/words_alphabetical.c, data_structures/linked_list/circular_linked_list.c, data_structures/linked_list/stack_using_linked_lists.c, developer_tools/min_printf.h, exercism/word_count/word_count.c, graphics/spirograph.c, machine_learning/kohonen_som_trace.c, searching/floyd_cycle_detection_algorithm.c, sorting/radix_sort_2.c
Fix some typos.
Notes: 
Fix some typos.
=> fix: Fix some typos.

data_structures/array/carray.c
Returns SUCCESS after successful switchValuesCArray
=> Return SUCCESS status

CONTRIBUTING.md, DIRECTORY.md
- Improve the contributing guidelines.
Notes:
=> docs: improve the contributing guidelines

leetcode/README.md, leetcode/src/118.c
=> added leetcode problem 118

leetcode/README.md, leetcode/src/2130.c
- [ :white_check_mark:] Added description of change
- [ :white_check_mark:] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [:white_check_mark: ] Relevant documentation/comments is changed or added
- [:white_check_mark: ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ :white_check_mark:] Search previous suggestions before making a new one, as yours may be a duplicate.
- [:white_check_mark: ] I acknowledge that all my contributions will be made under the project's license.
Notes: 
Add a leetcode question solution (2130)
=> feat: leetcode Maximum Twin Sum of a Linked List solution (2130)

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/stale.yml, CONTRIBUTING.md, README.md
- [x ] Added description of change
Notes: 
with reference to issue #1054 "[OTHER] Update Discord links", four discord links were updated to https://the-algorithms.com/discord/
=> Updates all Discord links closes #1054

leetcode/README.md, leetcode/src/62.c
=> Add  Solution of 62 ques of Leet Code

leetcode/README.md, leetcode/src/119.c
=> feat: add Leetcode problem 119

leetcode/README.md, leetcode/src/63.c
=> feat: add LeetCode problem 62

leetcode/README.md, leetcode/src/1019.c
- [✅  ] Added description of change
- [✅  ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [✅  ] Relevant documentation/comments is changed or added
- [ ✅ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ✅ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ✅ ] I acknowledge that all my contributions will be made under the project's license.
Notes: 
Leetcode Next Greater Node In Linked List solution (1019)
=> feat: leetcode Next Greater Node In Linked List solution (1019)

data_structures/vector.c
Added an implementation of Vector (like std::vector in C++) written in C in the Data Structures directory.
Notes: 
Hey @Panquesito7 ! Can you please review this PR? If there are any changes required please let me know and I'll implement them.
Also it'd be great if you could add a ``hacktoberfest-accepted`` tag to this PR.
Thank You!
=> Added a Vector implementation in data structures.

leetcode/README.md
Added solution link to Leetcode problem 62
=> fix: added solution link to problem 62

DIRECTORY.md, process_scheduling_algorithms/non_preemptive_priority_scheduling.c
Added New Section of Process Scheduling Algorithms, in which added non_preemptive_priority_scheduling approach
Notes:
=> Added non_preemptive_priority_scheduling in Process Scheduling Algorithm

leetcode/src/231.c
=> Power of Two improvements. avoid loop and recursion.

DIRECTORY.md, graphics/CMakeLists.txt
- Use FreeGlut's newest GitHub link.
TheAlgorithms/C-Plus-Plus#2397
Notes:
=> fix: use FreeGlut newest GitHub link

leetcode/DIRECTORY.md, leetcode/src/2304.c
=> add Minimum Path Cost in a Grid leetcode

leetcode/DIRECTORY.md, leetcode/src/985.c
=> add Sum of Even Numbers After Queries leetcode task

leetcode/DIRECTORY.md, leetcode/src/2024.c
=> add Maximize the Confusion of an Exam leetcode

leetcode/DIRECTORY.md, leetcode/src/1769.c
=> add Minimum Number of Operations to Move All Balls to Each Box leetcode

scripts/leetcode_directory_md.py
Fix indentation for leetcode_directory_md.py
Notes:
=> fix indentation for leetcode_directory_md.py

DIRECTORY.md, misc/hamming_distance.c
Add an algorithm to calculate the Hamming distance between two strings.
Notes:
=> feat: add hamming distance

leetcode/DIRECTORY.md, leetcode/src/567.c
=> add leetcode Permutation in String

data_structures/binary_trees/avl_tree.c
=> fix: Typo in avl_tree.c

leetcode/DIRECTORY.md, leetcode/src/540.c
Add leetcode problem 540 solution: Single Element in a Sorted Array
Notes:
=> feat: add LeetCode problem 540

DIRECTORY.md, hash/README.md, hash/hash_blake2b.c
Added my own implementation of the BLAKE2b hash function as described in [RFC 7693](https://www.rfc-editor.org/rfc/rfc7693). The function names and arguments are very faithful to the specification so readers can easily follow along.
Notes:
=> feat: implemented BLAKE2b cryptographic hashing algorithm

cipher/affine.c
An affine cipher is a linear transformation where encryption is of the form $E(x)=(ax+b) \text{ mod m }$ where $x$ is the character being encrypted and $m$ is the number of characters in the alphabet being used. Decryption is of the form $D(x) = a^{-1}(x-b) \text{ mod m}$ where $a^{-1}$ is the modular multiplicative inverse of $a$ modulo $m$, i.e., $a*a^{-1} \equiv 1 \text{ (mod m)}$.
Notes:  added affine cipher
=> feat: Added affine cipher

CONTRIBUTING.md, DIRECTORY.md
- Add self-test examples in the contributing guidelines.
TheAlgorithms/C-Plus-Plus/pull/2452
Notes:
=> docs: add self-test examples

.github/workflows/codeql.yml
- Update the CodeQL workflow (from the [original repository](https://github.com/github/codeql-action)).
Notes:
=> chore: update the CodeQL workflow

numerical_methods/secant_method.c
Added the secant method to numerical methods.
Notes:
=> feat: add secant method

.github/workflows/awesome_workflow.yml, DIRECTORY.md
- Label `Autochecks are failing` when the build fails.
None.
Notes:
=> feat: label when the build fails

.github/workflows/leetcode_directory_writer.yml, DIRECTORY.md
- Improve the LeetCode directory writer.
- Dependency-free (no more use of external actions).
- Runs only on this repository to ensure forks are not affected.
- Creates a pull request on the original repository (TheAlgorithms/C) if there are changes detected by using `git status --porcelain`.
Notes:
=> chore: improve the LeetCode directory writer

DIRECTORY.md, README.md
- Update workflow versions in `README.md`.
- For example, GNU 7.5.0 -> GNU 11.3.0.
- All the checks and versions can be seen at the latest [workflow run](https://github.com/TheAlgorithms/C/actions/workflows/awesome_workflow.yml). 
Notes:
=> docs: update workflow versions in `README.md`

.github/CODEOWNERS, CMakeLists.txt
This change is an update to use the latest version of CMake.
https://github.com/TheAlgorithms/C/issues/1271
Notes:
=> chore: update CMake version #1271

client_server/CMakeLists.txt
The include file for this function was missing so I added it in and updated the function call too.
Notes:
=> fix: Failed to execute cmake at client_server directory. #942

.github/workflows/awesome_workflow.yml, .github/workflows/directory_writer.yml
- Use directory workflow from the `scripts` repository.
- This contributes to #1214.
Notes:
=> feat: use directory workflow from the `scripts` repository
