Searches/Jump_Search.c
Sorts/HeapSort.c

heap sort is modified.
Please give me feedback.

#102 pull request heap sort is modified at input process to receive an integer directly.

---

Conversions/decimal _to_binary.c
Data Structures/linked_list/singly_link_list_deletion.c

fulls source code for insertion and deletion in singly linked list in c

fulls source code for insertion and deletion in singly linked list

---

conversions/toDecimal.c

In any to decimal conversions number should not be greater than or equal to base.

number invalid if number >= base

---

misc/FibonacciDP.c

Fixes Issue #284 
This adds Fibonacci Series using Dynamic Programming(DP)
Please merge this to your Repository . Have a nice day !

Fixes Issue #284

---

exercism/hello-world/hello_world.c

Fixed a critical flaw where `strcpy` would write the final NUL-terminator in an invalid location invoking Undefined Behavior. Allocated one extra byte to fix it.
Cleaned up the code as well in the process

+1 byte for the NUL-terminator

---

project_euler/Problem 07/sol.c

The correct format specifier for `size_t` is `%zu`. If C89 support is needed, `%lu` along with a cast to `unsigned long` will suffice.
Also added error checking for calloc.

Format specifier for size_t, calloc check

---

leetcode/README.md
leetcode/src/2.c
leetcode/src/21.c
leetcode/src/28.c
leetcode/src/4.c
leetcode/src/7.c
leetcode/src/8.c

Leetcode solutions for
2. Add Two Numbers
4. Median of Two Sorted Arrays
7. Reverse Integer
8. String to Integer (atoi)
21. Merge Two Sorted Lists
28. Implement strStr()
#249

Leetcode solutions

---

sorting/shellSort.c

re-written the code with only fewer lines making it more clear and consise.

updated shellSort.c

---

leetcode/src/5.c

Added #5 for leetcode, fixed typo in leetcode/readme

Add more solution for leetcode

---

misc/Prime.c

There are no prime numbers smaller than 2, but 2 itself is prime.

Correct and improve prime test

---

hash/hash.c
hash/hash.h
hash/test_program.c

My pull request #406 had an error, it made the CRC-32 Checksum 1 off.
With the Code of #406 
The function returned '1579384326' for name
With the new code it now returns '1579384327'  which is correct.

Fixed CRC-32 Error

---

README.md

Removed extra space from `decimal _to_binary`.
Though the PR might look too small, somebody once told me that any contribution to opensource is never too small.

Corrected function name

---

README.md

Added the heap structure in the README.md file ; it was already implemented but was missing in the doc.

added heap to readme; missing in the master README

---

CMakeLists.txt
misc/cantor_set.c
project_euler/problem_1/sol1.c
project_euler/problem_401/sol1.c
searching/binary_search.c

* Fixed `misc/cantor_set.c` for lgtm errors
* Fixed `searching/binary_search.c` for lgtm errors
* fixed cmake - removed `/Za` option for MSVC compiler
* added `details` section to `project_euler/problem_1/sol1.c`
Issue: #550, [lgtm alert link](https://lgtm.com/projects/g/TheAlgorithms/C/?mode=tree&ruleFocus=2157860312)
Notes:

[bugs/lgtm] code + doc fixes + lgtm corrections

---

numerical_methods/durand_kerner_roots.c
project_euler/problem_22/sol1.c
searching/modified_binary_search.c
sorting/bead_sort.c

* project Euler problem 22 lgtm error fix
* fix inconsistent use of `double` and `long double` in `durand_kerner_roots.c` 
* add docs & fix lgtm alerts in `bead_sort.c`
* #550 
* [project 22 - 1](https://lgtm.com/projects/g/TheAlgorithms/C/snapshot/4d0dbc401d67171d555d494c49a08e72303b5ba7/files/project_euler/problem_22/sol1.c?sort=name&dir=ASC&mode=heatmap#xa0d183509f9bbb35:1)
* [durange_kerner_roots](https://lgtm.com/projects/g/TheAlgorithms/C/snapshot/4d0dbc401d67171d555d494c49a08e72303b5ba7/files/numerical_methods/durand_kerner_roots.c?sort=name&dir=ASC&mode=heatmap)
* [bead_sort.c](https://lgtm.com/projects/g/TheAlgorithms/C/snapshot/4d0dbc401d67171d555d494c49a08e72303b5ba7/files/sorting/bead_sort.c?sort=name&dir=ASC&mode=heatmap#xdc9736f163b5f58d:1)
Notes:

[bugs] fixes for lgtm and improve docs

---

misc/prime.c
misc/strong_number.c

* fix doc
* add test
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/593"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shellhub/C.git/727169a13cdb8f2e2debce2b855d14cb1ce67172.svg" /></a>

[doc fix and add test]fix documentation in prime and strong number

---

.clang-format
.github/workflows/awesome_workflow.yml

Code formatting failed in CI steps by `clang-tidy`. Added explicit `clang-format` command. 
This is analogous to the issue TheAlgorithms/C-Plus-Plus#1032 and its corresponding solution TheAlgorithms/C-Plus-Plus#1052.
Tested in the above referenced PR and same commands used here as well.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/597"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C.git/8653cf4cb604fa2dca424ef2b1f16c7a6e8dd5dd.svg" /></a>

[bug fix] fix code formatting during CI

---

.github/workflows/awesome_workflow.yml

CI checks are repeatedly failing due to non-standard C code in the windows SDK.
This will remove CI build checks on windows OS and thus eliminate the issues.
Closes #794 
Closes 
- ~[ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)~
- ~[ ] Added tests and example, test must pass~
- ~[ ] Relevant documentation/comments is changed or added~
Notes:

[CI - bugfix] remove windows builds

---

games/tic_tac_toe.c

Issue: #729 
As **mentioned** in the issue , The piece code listed below throws the program into an loop (from `line 247`) if an **invalid** character is entered.
```diff
else
{
+            int n = check_placex();
-             printf("Invalid move\n");
-            printf("Enter new position : ");
-            scanf("%d", &n1);
+           placex(n);
-            placex(n1);
}
}
else
{
-        printf("Invalid move \n");
+       int n = check_placex();
-        printf("Enter new position : ");
-        scanf("%d", &n1);
+       placex(n);
-        placex(n1);
}
}
```
```diff
+ int *stored_pos = NULL;
```
`line 47`:
```diff
+  stored_pos = (int*)calloc(9,sizeof(int))
```
`line 331`, `line 308` & `line 278`  
example: 
```diff
+ stored_pos[e] = 1;
```
`line 75`
```diff
+ free(stored_pos); …
```

fix: several bugs on games/tic_tac_toe.c

---

data_structures/heap/max_heap.c

Previously after execution it was throwing error that INT_MIN is not declared. Added limits.h header file to fix that error. 
Closes #758 
Notes:

fix: Added `limits.h` in `data_structures/heap/max_heap.c`

---

DIRECTORY.md
client_server/tcp_full_duplex_client.c
client_server/tcp_full_duplex_server.c

Implemented a Full Duplex Communication server client model using a TCP socket
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/856"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

TCP Full Duplex Server Client Communication

---

.github/workflows/awesome_workflow.yml

- Reverts TheAlgorithms/C#901. @straight-into-the-wall.
- See https://github.com/TheAlgorithms/C/pull/897#issuecomment-955181111 for the explanation.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/907"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Revert "fix: #898 another fix for Awesome workflow nodir_files  problem"

---

.gitpod.yml

I think there is no need to lock extensions' version.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/915"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

gitpod: don't lock extensions' version

---

sorting/merge_sort.c

Merge sort does not work properly. To reproduce the bug input 6, 5, 4, 3, 2, 1 the output would be 2, 3, 1, 4, 5, 6.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/921"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: merge sort bug

---

sorting/quick_sort.c

Free the allocated resources by malloc
It is a  good practice and example to always free the allocated resources
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/923"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: free the allocated resources in quick sort

---

sorting/heap_sort_2.c

>  **_parentIndex = [childIndex / 2]_** for **_1-based indexing_** , but here we are doing the process in **_0-based indexing_**, so the _**parentIndex**_ should be  = _**[(childIndex - 1) / 2]**_ 
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/914"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: fixed index of parent in sorting/heap_sort_2.c

---

data_structures/array/carray.c

Added a body to the empty if-block in the `updateValueCArray()` function of the CArray implementation. The function now updates the element at the given index `position` with `value`  and returns `SUCCESS` upon doing so. 
Closes issue #932 
Notes: Fixed the empty if-block in function `updateValueCArray()`
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/933"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: update value at index and return `SUCCESS` (#932)

---

data_structures/dynamic_array/dynamic_array.c

**Call to free() after realloc() removed, avoiding undefined behavior.**
The call to realloc() already frees the previously allocated memory if necessary.
By the man page of realloc(): _"f the area pointed to was moved, a free(ptr) is done.",_
and free(): _"If free(ptr) has already been called before, undefined behavior occurs."._
- [ x] Added description of change(https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
Notes: Removed call to free() after realloc()

fix: Removed double / unintended free

---

leetcode/DIRECTORY.md
leetcode/src/98.c

add Validate Binary Search Tree

---

leetcode/DIRECTORY.md
leetcode/src/669.c

add leetcode Trim a Binary Search Tree

---

leetcode/DIRECTORY.md
leetcode/src/1137.c

add leetcode n-th Tribonacci number

---

CMakeLists.txt
math/CMakeLists.txt

The `math` directory didn't have a `CMakeLists.txt` and wasn't added as subdirectory in the root `CMakeLists.txt`. So I fixed that
Notes:  `math` now builds

chore: add `math` to CMake lists

---

leetcode/DIRECTORY.md
leetcode/src/434.c

Adds solution of problem 434 for leetcode. Beats 100% Time, 97.18% space

feat: add LeetCode problem 434

---

cipher/affine.c
games/hangman.c
games/words.txt

C implementation of the traditional hangman game (with duck graphic).
Issue #967 
Notes: 
Test cases may need to be improved.

feat: added hangman game #967

---

CMakeLists.txt
DIRECTORY.md
dynamic_programming/CMakeLists.txt
dynamic_programming/lcs.c

- Add the `dynamic_programming` folder to CMake lists.
Notes:

feat: add `dynamic_programming` to CMake lists

---

data_structures/list/list.c

I changed the return value of n in List_length to reflect the number of items inside the list, so a newly initialized list will return a length of 0.  To prevent items in List_toArray from being cut off, I added one back to n at the beginning of the List_toArray function.
Notes:

changed list length to reflect contents of the list

---

leetcode/src/69.c

Here is the code for the problem 69 of leetcode as there are many ways to do it we programmers need to find the most optimal way to solve a problem statement so i used binary-search approach inorder to solve it. All  suggestions are accepted!!!
Notes:

feat: add LeetCode problem 69

---

.github/workflows/leetcode_directory_writer.yml

- Fix LeetCode directory writer.
- The ` || true` code is needed in case there are no changes to make or the PR already exists so that the script doesn't fail and exits completely.
Notes:

fix: LeetCode directory writer

---

.github/workflows/awesome_workflow.yml
CMakeLists.txt
DIRECTORY.md
client_server/CMakeLists.txt
client_server/bool.h
client_server/fork.h
client_server/remote_command_exec_udp_client.c
client_server/remote_command_exec_udp_server.c
client_server/tcp_full_duplex_client.c
client_server/tcp_full_duplex_server.c
client_server/tcp_half_duplex_client.c
client_server/tcp_half_duplex_server.c
developer_tools/min_printf.h
dynamic_programming/matrix_chain_order.c
graphics/CMakeLists.txt
searching/exponential_search.c

- Add Windows builds back.
- Thanks to @realstealthninja for their help!
- Closes #1274.
Notes:

feat: add Windows CI back
